package dev.thestbar.tunify.ui.theme

import androidx.compose.ui.graphics.Color

// ── Dark scheme ───────────────────────────────────────────────────────
val DarkPrimary                = Color(0xFFFFB4A0)
val DarkOnPrimary              = Color(0xFF5E1606)
val DarkPrimaryContainer       = Color(0xFF88301C)
val DarkOnPrimaryContainer     = Color(0xFFFFDBD0)
val DarkSecondary              = Color(0xFFE7BEAF)
val DarkOnSecondary            = Color(0xFF442016)
val DarkSecondaryContainer     = Color(0xFF57403A)
val DarkOnSecondaryContainer   = Color(0xFFFFDCD1)
val DarkTertiary               = Color(0xFF7AD78F)   // in-tune green
val DarkOnTertiary             = Color(0xFF00391C)
val DarkTertiaryContainer      = Color(0xFF1F4A2E)
val DarkOnTertiaryContainer    = Color(0xFF96F3A9)
val DarkBackground             = Color(0xFF17120F)
val DarkOnBackground           = Color(0xFFECE0D9)
val DarkSurface                = Color(0xFF17120F)
val DarkOnSurface              = Color(0xFFECE0D9)
val DarkOnSurfaceVariant       = Color(0xFFB6A79F)
val DarkOutline                = Color(0xFF80726A)
val DarkOutlineVariant         = Color(0xFF4D413B)
val DarkSurfaceContainer       = Color(0xFF231B17)
val DarkSurfaceContainerHigh   = Color(0xFF2E251F)
val DarkSurfaceContainerHighest= Color(0xFF3A302A)
val DarkSurfaceContainerLow    = Color(0xFF1F1714)
val DarkSurfaceContainerLowest = Color(0xFF0F0B09)
val DarkError                  = Color(0xFFFFB4AB)
val DarkOnError                = Color(0xFF690005)
val DarkErrorContainer         = Color(0xFF93000A)
val DarkOnErrorContainer       = Color(0xFFFFDAD6)

// ── Light scheme ──────────────────────────────────────────────────────
val LightPrimary               = Color(0xFFA5402A)
val LightOnPrimary             = Color(0xFFFFFFFF)
val LightPrimaryContainer      = Color(0xFFFFDBD0)
val LightOnPrimaryContainer    = Color(0xFF3D0900)
val LightSecondary             = Color(0xFF77574E)
val LightOnSecondary           = Color(0xFFFFFFFF)
val LightSecondaryContainer    = Color(0xFFFBD9CD)
val LightOnSecondaryContainer  = Color(0xFF2D160E)
val LightTertiary              = Color(0xFF2E7D52)   // in-tune green
val LightOnTertiary            = Color(0xFFFFFFFF)
val LightTertiaryContainer     = Color(0xFFB6F0C6)
val LightOnTertiaryContainer   = Color(0xFF002115)
val LightBackground            = Color(0xFFFFF8F6)
val LightOnBackground          = Color(0xFF281812)
val LightSurface               = Color(0xFFFFF8F6)
val LightOnSurface             = Color(0xFF281812)
val LightOnSurfaceVariant      = Color(0xFF6C5A52)
val LightOutline               = Color(0xFF9E8C83)
val LightOutlineVariant        = Color(0xFFD8C5BC)
val LightSurfaceContainer      = Color(0xFFF8EAE4)
val LightSurfaceContainerHigh  = Color(0xFFF2E4DE)
val LightSurfaceContainerHighest= Color(0xFFECDED7)
val LightSurfaceContainerLow   = Color(0xFFFDF1EC)
val LightSurfaceContainerLowest= Color(0xFFFFFFFF)
val LightError                 = Color(0xFFBA1A1A)
val LightOnError               = Color(0xFFFFFFFF)
val LightErrorContainer        = Color(0xFFFFDAD6)
val LightOnErrorContainer      = Color(0xFF410002)
